image: node:16

stages:
  - dev-src-build
  - dev-docker-build
  - dev-iac-apply
  - prd-src-build
  - prd-docker-build
  - prd-iac-plan
  - prd-iac-apply

default:
  interruptible: true

dev-src-build:
  stage: dev-src-build
  script:
    - export ENDPOINT_CMS=https://cms.dev.midowe.co.mz/api
    - export ENDPOINT_ACCOUTING=https://eugqgyjdksk2hoi7rj6b23zjti0grskw.lambda-url.af-south-1.on.aws
    - npm ci
    - npm run build
  artifacts:
    paths:
      - .output
  only:
    - main

dev-docker-build:
  stage: dev-docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/develop:latest .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/develop:latest
  only:
    - main

.tf-init-dev:
  before_script:
    - apt-get update && apt-get install software-properties-common curl openssh-client -y
    # Configs and Secrets
    - export TF_VAR_environment=dev
    - export TF_VAR_container_port=33000
    - export TF_VAR_image_tag=$CI_REGISTRY_IMAGE/develop:latest
    - export TF_VAR_registry_username=$REGISTRY_USERNAME
    - export TF_VAR_registry_password=$REGISTRY_PASSWORD
    # Setup SSH
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_SAFEHOUZE" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Terraform
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt-get update && apt-get install terraform -y
    - terraform version
    - |
      terraform -chdir=.iac init \
      -backend=true \
      -backend-config="key=midowe-web-dev/terraform.tfstate" \
      -force-copy

dev-iac-apply:
  stage: dev-iac-apply
  extends: .tf-init-dev
  interruptible: false
  script:
    - terraform -chdir=.iac validate
    - terraform -chdir=.iac plan -out=dev-env.tfplan
    - terraform -chdir=.iac show -json dev-env.tfplan > .iac/dev-env.tfplan.json
    - terraform -chdir=.iac apply -auto-approve dev-env.tfplan
    - terraform -chdir=.iac output -json > .iac/dev-env.tfoutput.json
  artifacts:
    paths:
      - ".out/*"
      - ".iac/*.json"
      - ".iac/*.tfplan"
      - ".iac/.terraform/providers"
  only:
    - main

prd-src-build:
  stage: prd-src-build
  script:
    - export ENDPOINT_CMS=https://cms.midowe.co.mz/api
    - export ENDPOINT_ACCOUTING=https://xlhofsmgf4o3xtpleqam77sd240braxu.lambda-url.af-south-1.on.aws
    - npm ci
    - npm run build
  artifacts:
    paths:
      - .output
  only:
    - main

prd-docker-build:
  stage: prd-docker-build
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker build -t $CI_REGISTRY_IMAGE/main:latest .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $CI_REGISTRY_IMAGE/main:latest
  dependencies:
    - prd-src-build
  only:
    - main

.tf-init-prd:
  before_script:
    - apt-get update && apt-get install software-properties-common curl openssh-client -y
    # Configs and Secrets
    - export TF_VAR_environment=prd
    - export TF_VAR_container_port=33500
    - export TF_VAR_image_tag=$CI_REGISTRY_IMAGE/main:latest
    - export TF_VAR_registry_username=$REGISTRY_USERNAME
    - export TF_VAR_registry_password=$REGISTRY_PASSWORD
    # Setup SSH
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_SAFEHOUZE" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Terraform
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt-get update && apt-get install terraform -y
    - terraform version
    - |
      terraform -chdir=.iac init \
      -backend=true \
      -backend-config="key=midowe-web-prd/terraform.tfstate" \
      -force-copy

prd-iac-plan:
  stage: prd-iac-plan
  extends: .tf-init-prd
  script:
    - terraform -chdir=.iac plan -out=prd-env.tfplan
    - terraform -chdir=.iac show -json prd-env.tfplan > .iac/prd-env.tfplan.json
  artifacts:
    paths:
      - ".out/*"
      - ".iac/*.json"
      - ".iac/*.tfplan"
      - ".iac/.terraform/providers"
  dependencies:
    - prd-docker-build
  only:
    - main

prd-iac-apply:
  stage: prd-iac-apply
  extends: .tf-init-prd
  interruptible: false
  script:
    - terraform -chdir=.iac apply -auto-approve prd-env.tfplan
    - terraform -chdir=.iac output -json > .iac/prd-env.tfoutput.json
  artifacts:
    paths:
      - ".out/*"
      - ".iac/*.json"
      - ".iac/*.tfplan"
      - ".iac/.terraform/providers"
  dependencies:
    - prd-iac-plan
  only:
    - main
  when: manual
