image: golang:1.18.2-buster

variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - all-lint
  - docker-build
  - dev-iac-plan
  - dev-iac-apply
  - prd-iac-plan
  - prd-iac-apply

default:
  interruptible: true

.tf-init-dev:
  before_script:
    - apt-get update && apt-get install software-properties-common curl openssh-client -y
    # Configs and Secrets
    - export TF_VAR_environment=dev
    - export TF_VAR_container_port=33000
    - export TF_VAR_image_tag=$TAG_COMMIT
    # Setup SSH
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY_SAFEHOUZE" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # Terraform
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt-get update && apt-get install terraform -y
    - terraform version
    - |
      terraform -chdir=.iac init \
      -backend=true \
      -backend-config="key=midowe-web-dev/terraform.tfstate" \
      -force-copy

dev-iac-plan:
  stage: dev-iac-plan
  extends: .tf-init-dev
  script:
    - terraform -chdir=.iac plan -out=dev-env.tfplan
    - terraform -chdir=.iac show -json dev-env.tfplan > .iac/dev-env.tfplan.json
  artifacts:
    paths:
      - ".out/*"
      - ".iac/*.json"
      - ".iac/*.tfplan"
      - ".iac/.terraform/providers"
  only:
    - develop
    - main
