image: debian:buster

variables:
  TAG_COMMIT: $CI_REGISTRY_IMAGE/$CI_COMMIT_REF_NAME:$CI_COMMIT_SHORT_SHA

stages:
  - all-lint
  - docker-build
  - dev-iac-plan
  - dev-iac-apply
  - prd-iac-plan
  - prd-iac-apply

docker-build:
  stage: docker-build
  image: docker:latest
  services:
    - docker:dind
  interruptible: true
  script:
    - docker build -t $TAG_COMMIT .
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY
    - docker push $TAG_COMMIT
  only:
    - develop
    - main

.tf-init-dev:
  before_script:
    # Configs and Secrets
    - export TF_VAR_environment=dev
    - export TF_VAR_container_port=33000
    - export TF_VAR_image_tag=$TAG_COMMIT
    # Setup private key
    - echo $SSH_PRIVATE_KEY_SAFEHOUZE > id_rsa.key
    # Terraform
    - apt-get update && apt-get install software-properties-common -y
    - curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
    - apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
    - apt-get update && apt-get install terraform -y
    - terraform version
    - |
      terraform -chdir=.iac init \
      -backend=true \
      -backend-config="key=midowe-web-dev/terraform.tfstate" \
      -force-copy

dev-iac-lint:
  stage: all-lint
  extends: .tf-init-dev
  script:
    - terraform -chdir=.iac validate
  artifacts:
    paths:
      - ".iac/.terraform/providers"

dev-iac-plan:
  stage: dev-iac-plan
  extends: .tf-init-dev
  script:
    - terraform -chdir=.iac plan -out=dev-env.tfplan
    - terraform -chdir=.iac show -json dev-env.tfplan > .iac/dev-env.tfplan.json
  artifacts:
    paths:
      - ".out/*"
      - ".iac/*.json"
      - ".iac/*.tfplan"
      - ".iac/.terraform/providers"
  only:
    - develop
    - main

dev-iac-apply:
  stage: dev-iac-apply
  extends: .tf-init-dev
  script:
    - terraform -chdir=.iac apply -auto-approve dev-env.tfplan
    - terraform -chdir=.iac output -json > .iac/dev-env.tfoutput.json
  artifacts:
    paths:
      - ".out/*"
      - ".iac/*.json"
      - ".iac/*.tfplan"
      - ".iac/.terraform/providers"
  only:
    - develop
    - main
